
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:26 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:26 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS
      Id flags:  
      
      The output was:
      0
      Versão do MSBuild 17.7.2+d6990bcfa para .NET Framework
      Compilação de 06/03/2025 16:36:21 iniciada.
      
      Projeto "C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj" no nó 1 (destinos padrão).
      PrepareForBuild:
        Criando o diretório "Debug\\".
        Criando o diretório "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Criando "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
        Tocando "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Excluindo o arquivo "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Tocando "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Projeto de compilação pronto "C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj" (destinos padrão).
      
      Compilação com êxito.
          0 Aviso(s)
          0 Erro(s)
      
      Tempo Decorrido 00:00:00.59
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/3.27.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:26 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS;/GR;/EHsc
      Id flags:  
      
      The output was:
      0
      Versão do MSBuild 17.7.2+d6990bcfa para .NET Framework
      Compilação de 06/03/2025 16:36:22 iniciada.
      
      Projeto "C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" no nó 1 (destinos padrão).
      PrepareForBuild:
        Criando o diretório "Debug\\".
        Criando o diretório "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Criando "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
        Tocando "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Excluindo o arquivo "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Tocando "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Projeto de compilação pronto "C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (destinos padrão).
      
      Compilação com êxito.
          0 Aviso(s)
          0 Erro(s)
      
      Tempo Decorrido 00:00:00.64
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/3.27.4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:26 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/CMakeScratch/TryCompile-tgb4t6"
      binary: "C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/CMakeScratch/TryCompile-tgb4t6"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/CMakeScratch/TryCompile-tgb4t6'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_dcaba.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Versão do MSBuild 17.7.2+d6990bcfa para .NET Framework
        Compilação de 06/03/2025 16:36:23 iniciada.
        
        Projeto "C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\CMakeScratch\\TryCompile-tgb4t6\\cmTC_dcaba.vcxproj" no nó 1 (destinos padrão).
        PrepareForBuild:
          Criando o diretório "cmTC_dcaba.dir\\Debug\\".
          Criando o diretório "C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\CMakeScratch\\TryCompile-tgb4t6\\Debug\\".
          Criando o diretório "cmTC_dcaba.dir\\Debug\\cmTC_dcaba.tlog\\".
        InitializeBuildStatus:
          Criando "cmTC_dcaba.dir\\Debug\\cmTC_dcaba.tlog\\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
          Tocando "cmTC_dcaba.dir\\Debug\\cmTC_dcaba.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_dcaba.dir\\Debug\\\\" /Fd"cmTC_dcaba.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Versão 19.37.32822 para x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation. Todos os direitos reservados.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_dcaba.dir\\Debug\\\\" /Fd"cmTC_dcaba.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\CMakeScratch\\TryCompile-tgb4t6\\Debug\\cmTC_dcaba.exe" /INCREMENTAL /ILK:"cmTC_dcaba.dir\\Debug\\cmTC_dcaba.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/CMakeScratch/TryCompile-tgb4t6/Debug/cmTC_dcaba.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/CMakeScratch/TryCompile-tgb4t6/Debug/cmTC_dcaba.lib" /MACHINE:X64  /machine:x64 cmTC_dcaba.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_dcaba.vcxproj -> C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\CMakeScratch\\TryCompile-tgb4t6\\Debug\\cmTC_dcaba.exe
        FinalizeBuildStatus:
          Excluindo o arquivo "cmTC_dcaba.dir\\Debug\\cmTC_dcaba.tlog\\unsuccessfulbuild".
          Tocando "cmTC_dcaba.dir\\Debug\\cmTC_dcaba.tlog\\cmTC_dcaba.lastbuildstate".
        Projeto de compilação pronto "C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\CMakeScratch\\TryCompile-tgb4t6\\cmTC_dcaba.vcxproj" (destinos padrão).
        
        Compilação com êxito.
            0 Aviso(s)
            0 Erro(s)
        
        Tempo Decorrido 00:00:00.56
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:26 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/CMakeScratch/TryCompile-re3zsg"
      binary: "C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/CMakeScratch/TryCompile-re3zsg"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/CMakeScratch/TryCompile-re3zsg'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_9e98a.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Versão do MSBuild 17.7.2+d6990bcfa para .NET Framework
        Compilação de 06/03/2025 16:36:24 iniciada.
        
        Projeto "C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\CMakeScratch\\TryCompile-re3zsg\\cmTC_9e98a.vcxproj" no nó 1 (destinos padrão).
        PrepareForBuild:
          Criando o diretório "cmTC_9e98a.dir\\Debug\\".
          Criando o diretório "C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\CMakeScratch\\TryCompile-re3zsg\\Debug\\".
          Criando o diretório "cmTC_9e98a.dir\\Debug\\cmTC_9e98a.tlog\\".
        InitializeBuildStatus:
          Criando "cmTC_9e98a.dir\\Debug\\cmTC_9e98a.tlog\\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
          Tocando "cmTC_9e98a.dir\\Debug\\cmTC_9e98a.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_9e98a.dir\\Debug\\\\" /Fd"cmTC_9e98a.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Versão 19.37.32822 para x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation. Todos os direitos reservados.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_9e98a.dir\\Debug\\\\" /Fd"cmTC_9e98a.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\CMakeScratch\\TryCompile-re3zsg\\Debug\\cmTC_9e98a.exe" /INCREMENTAL /ILK:"cmTC_9e98a.dir\\Debug\\cmTC_9e98a.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/CMakeScratch/TryCompile-re3zsg/Debug/cmTC_9e98a.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/henri/Desktop/BubbleDelay/BubbleDelay/juce/tools/CMakeFiles/CMakeScratch/TryCompile-re3zsg/Debug/cmTC_9e98a.lib" /MACHINE:X64  /machine:x64 cmTC_9e98a.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_9e98a.vcxproj -> C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\CMakeScratch\\TryCompile-re3zsg\\Debug\\cmTC_9e98a.exe
        FinalizeBuildStatus:
          Excluindo o arquivo "cmTC_9e98a.dir\\Debug\\cmTC_9e98a.tlog\\unsuccessfulbuild".
          Tocando "cmTC_9e98a.dir\\Debug\\cmTC_9e98a.tlog\\cmTC_9e98a.lastbuildstate".
        Projeto de compilação pronto "C:\\Users\\henri\\Desktop\\BubbleDelay\\BubbleDelay\\juce\\tools\\CMakeFiles\\CMakeScratch\\TryCompile-re3zsg\\cmTC_9e98a.vcxproj" (destinos padrão).
        
        Compilação com êxito.
            0 Aviso(s)
            0 Erro(s)
        
        Tempo Decorrido 00:00:00.61
        
      exitCode: 0
...
